modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="tradingpost_easyvillagers_compat"
version="1.0.1"
displayName="Trading Post + Easy Villagers Compatibility"
authors="AxelR"
description='''Allows Trading Post to trade with villagers stored in Easy Villagers Trader blocks.'''

[[dependencies.tradingpost_easyvillagers_compat]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.tradingpost_easyvillagers_compat]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.tradingpost_easyvillagers_compat]]
modId="tradingpost"
type="required"
versionRange="[21.1.1,21.1.2)"
ordering="AFTER"
side="BOTH"

[[dependencies.tradingpost_easyvillagers_compat]]
modId="easy_villagers"
type="required"
versionRange="[1.21.1-1.1.42,1.21.1-1.1.43)"
ordering="AFTER"
side="BOTH"

[[dependencies.tradingpost_easyvillagers_compat]]
modId="infinitetrading"
type="optional"
versionRange="[5.0,6.0)"
ordering="AFTER"
side="BOTH"

[[mixins]]
config="tradingpost_easyvillagers_compat.mixins.json"
